bot:
  # Discord botunuzun tokeni
  token: 'MTE5NjkzMjEzMzg5ODQzMjU4Mg.G0rTsr.4l3ZhbvzpdVx_u20HqR7WcHV2DElvB_BOb5SY0'
  # Discord botunuzun application idsi
  id: '1196932133898432582'
  # Discord botunun durum kÄ±smÄ±
  status:
    # Discord botunun aÃ§Ä±klma kÄ±smÄ±ndaki event; playing = Oynuyor, streaming = YayÄ±nda, listening = Dinliyor, watching = Ä°zliyor, competing = YarÄ±ÅŸmada yarÄ±ÅŸÄ±yor.
    activity: 'listening'
    # Discord botunun aÃ§Ä±klama yazÄ±sÄ±; %onDutyPolice% yazarak aktif mesaideki memurlarÄ±n sayÄ±sÄ±nÄ± gÃ¶sterebilirsiniz.
    text: '/aktif-mesai'
    # Discord botunun aÃ§Ä±klma kÄ±smÄ±ndaki event streaming olarak ayarlanÄ±rsa aÅŸaÄŸÄ±daki twitch kÄ±smÄ±nÄ± doldurunuz.
    twitch: ''
    # Discord botunun aktiflik kÄ±smÄ±; online = Aktif, idle = BoÅŸta, dnd = RahatsÄ±z Etmeyin, invisible = Ã‡evrimdÄ±ÅŸÄ±.
    status: 'online'
guild:
  # Discord sunucunuzun idsi
  id: '1179154804132552835'
settings:
  departmentName: 'Blaine County Sherrif Office'
  departmentLogo: 'https://static.wikia.nocookie.net/rde/images/e/e1/Lore-friendly-bcso_logo.png/revision/latest?cb=20171218164800'
  departmentBanner: 'https://cdn.discordapp.com/attachments/1195881542740889680/1197007429049798716/sadad.png?ex=65b9b30a&is=65a73e0a&hm=0f3f21069b1d7ad8ce666c37ecee744a26c5b82d2cf020c81b0c2ad66438f8d8&'
  departmentColor: '#ffff00'
  roles:
    # RÃ¼tbe rollerinin idleri
    officers: ['1179154804132552844', '1179154804153532416', '1179154804153532417', '1179154804153532418', '1179154804153532419', '1179154804153532420', '1179154804153532421', '1179154804153532422', '1179169637825527838', '1179154804187082887']
  channels:
    # Log kanalÄ±nÄ±n idsi
    log: '1197006111551795291'
  # Mesaj iÃ§erikelrinde kulanÄ±lan emojiler, ğŸ“‹ ÅŸeklinde, :emojiAdÄ±: ÅŸeklinde veya idsiyle kullanÄ±labilir.
  emojis:
    department: 'ğŸ‘®'
    on: 'ğŸŸ©'
    off: 'ğŸŸ¥'
    warning: 'âš ï¸'
    info: 'ğŸ“‹'
    clock: 'â²ï¸'
commands:
    # Aktif mesaideki Ã¼yeleri gÃ¶steren komut
    activeDuty:
      # Bu komutu kullanabilmek iÃ§in gereken rol
      requiredRole: '1197005523233550366'
